path planning launch file - 1st commit
UOA-FSAE/autonomous pull request #139
Opened 2024-11-14 04:26 UTC by Tanish29

# Description
Issue #

path planning launch file completed (without node parameters)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-17 03:38 UTC, Zane-Larking requested changes

2024-11-17 03:38 UTC, Zane-Larking commented on src/moa/moa_driver/launch/moa_driver.launch.py
Can this launch file be called can_launch.py. There are likely to be additional driver packages in this folder.

2024-11-17 03:38 UTC, Zane-Larking commented on src/moa/moa_driver/setup.py
Good catch.

2024-11-17 03:38 UTC, Zane-Larking commented on src/perception/sythesis/cone_mapping/launch/cone_mapping.launch.py
> +    node = OpaqueFunction(function=get_node, args=[package_name, mappers])    # get a list of actions
Didn't know this was a thing. Looks really clean, I'll have to start using it myself.

2024-11-17 03:38 UTC, Zane-Larking commented on src/perception/sythesis/cone_mapping/launch/cone_mapping.launch.py
I like it. Very Clean. It would pay to add a comment at the top about it allowing the user to select which of the mappers is run.

2024-11-19 07:22 UTC, Tanish29 commented on src/moa/moa_driver/launch/moa_driver.launch.py
this is not part of path planning?

2024-11-19 07:25 UTC, Tanish29 commented on src/moa/moa_driver/launch/moa_driver.launch.py
bruh y did pang commit on this branch?!

2024-12-02 07:14 UTC, merged