control folder, controller package, common launch file
UOA-FSAE/autonomous pull request #143
Opened 2024-11-17 02:55 UTC by Siva-Sriram

# Description

- added control hierarchy folder and controller package
- controller package contains nodes in the control pipeline: namely pure_pursuit, head_to_goal, and stanley
- launch file created with stanley as default if no arguments provided

2024-11-19 08:23 UTC, Tanish29 requested changes
please resolve my comments - Tanish

2024-11-19 08:23 UTC, Tanish29 commented on src/control/controller/setup.py
> +    data_files=[
have you tested having 2 "data_files" works?

2024-11-19 08:23 UTC, Tanish29 commented on src/control/controller/launch/controller_launch.py
> +            parameters=[{'controller_type': controller_type}]
the parameters argument is if the controller_type node has parameters. Is controller_type a parameter in the node?
Everything else looks good, nice!

2024-11-19 08:23 UTC, Tanish29 commented on src/action/stanley_controller/launch/stanley_controller_launch.py
> +from launch import LaunchDescription
why is the Stanley controller here if it's copied to the controller package?

2024-12-02 07:35 UTC, Zane-Larking requested changes

2024-12-02 07:35 UTC, Zane-Larking commented on src/action/stanley_controller/launch/stanley_controller_launch.py
> +from launch import LaunchDescription
This should be deleted

2024-12-02 07:35 UTC, Zane-Larking commented on src/control/controller/package.xml
There are some missing dependencies:
ackermann_msgs
moa_msgs
geometry_msgs

2025-04-13 03:07 UTC, closed without merging